[package]
name = "nelly-runner"
version.workspace = true
edition = "2024"

[features]
default = ["build-in-cargo"]
build-in-cargo = []

[dependencies]
nelly.path = ".."
generated.path = "../generated"
anyhow.workspace = true
